server:
  port: 8088

spring:
  application:
    name: api-gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      routes:
        - id: auth-service
          uri: ${AUTH}  #http://localhost:9090/api/v1/auth/dologin http://localhost:9090
          predicates:
            - Path=/auth/**    #gelen isteği yakalar: http://localhost/auth/dologin
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: userprofile-service
          uri: ${USER}  #http://localhost:9090/api/v1/auth/dologin http://localhost:9093
          predicates:
            - Path=/userprofile/**    #gelen isteği yakalar: http://localhost/auth/dologin
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      default-filters:
        - RewritePath= /(?<segment>.*) , /api/v1/$\{segment}
