server:
  port: 9093
spring:
  security:
    user:
      name: mucahit
      password: 1234
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root
  data:
    mongodb:
      host: localhost
      port: 27017
      database: FacebookDB
      username: Java7User
      password: root

my-application:
  redis-host: localhost
  jwt:
    secret-key: "nI5afruwE##E3-#&-&If65s!6WrlB#&PhLtI4ecrA?iBr+4Ra+1pa?e3LYAK688$"
    secret-key-env: ${SECRETKEY}
